# Generated by Django 5.2.4 on 2025-09-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
